version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    command: "/app/build/server"
    depends_on:
      - redis
    environment: {}
    ports:
      - 4000:4000
    volumes:
      - go-pkg-cache:/go
      - .:/app
  redis:
    image: redis:6.2.4-alpine
    container_name: 'redis'
volumes:
  go-pkg-cache:
    driver: local
