version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    command: "/app/build/server"
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: decks
      POSTGRES_SSLMODE: disable
    ports:
      - 4000:4000
    volumes:
      - go-pkg-cache:/go
      - .:/app
  redis:
    image: redis:6.2.4-alpine
    container_name: 'redis'
  postgres:
    image: postgres:16-alpine
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: decks
volumes:
  go-pkg-cache:
    driver: local
