version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    environment: {}
    command: "/app/build/server"
    ports:
      - 4000:4000
    volumes:
      - go-pkg-cache:/go
      - .:/app
volumes:
  go-pkg-cache:
    driver: local
